### ISSUE TITLE
Add Essential Documentation for Hacktoberfest Eligibility

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#74]
## Description

To make the repository eligible for Hacktoberfest and encourage contributions from the open-source community, add essential documentation pages. These pages will help new contributors understand the project, how to contribute, and the guidelines for participation.

## Tasks

1. **Create `README.md`:**

   - Provide an overview of the project, including its purpose, features, and technologies used.
   - Add sections such as:
     - Project Introduction
     - Getting Started (installation and setup instructions)
     - Usage Instructions (how to run the project locally)
     - API Reference (if applicable)
     - Contributing Guidelines
     - License Information
   - Include badges for Hacktoberfest participation, build status, and license.

2. **Create `CONTRIBUTING.md`:**

   - Provide clear instructions on how to contribute to the repository.
   - Include the following sections:
     - How to fork and clone the repository.
     - Branch naming conventions (e.g., `feature/`, `bugfix/`, `docs/`).
     - How to create a pull request (PR).
     - Code formatting and style guide (e.g., Prettier, ESLint).
     - Link to `CODE_OF_CONDUCT.md`.

3. **Create `CODE_OF_CONDUCT.md`:**

   - Establish community guidelines to ensure a welcoming and inclusive environment for contributors.
   - Use the [Contributor Covenant](https://www.contributor-covenant.org/) template as a starting point.
   - Include guidelines on expected behaviour and how to report issues.

4. **Create `LICENSE`:**

   - Choose an appropriate open-source license (e.g., MIT, Apache 2.0) to clarify how others can use the project.
   - Add the license text to the `LICENSE` file.

5. **Update `.github/ISSUE_TEMPLATE.md` (Optional):**

   - Create a template for submitting issues to ensure all necessary details are included (e.g., description, steps to reproduce, expected behaviour).
   - This can help maintain consistency in issue reports and make it easier for contributors to get started.

6. **Update `.github/PULL_REQUEST_TEMPLATE.md` (Optional):**
   - Create a template for pull requests that includes sections such as:
     - What changes have been made?
     - Screenshots (if applicable).
     - Related issue or task.
     - Checklist for tests and code quality checks.

## Acceptance Criteria

- `README.md` includes a detailed overview of the project, contributing instructions, and a Hacktoberfest badge.
- `CONTRIBUTING.md` outlines steps to contribute, PR process, and coding standards.
- `CODE_OF_CONDUCT.md` is based on the Contributor Covenant and outlines acceptable behaviour.
- `LICENSE` file is added with the chosen license.
- Optional: Issue and PR templates are available to guide contributors.

Related: 
- https://github.com/ansopedia/creator-studio/issues/12
- https://github.com/ansopedia/notification-service/issues/9

**Comment by Daksh-134** [comment]
Hi @sanjaysah101 ,pls assign this issue to me if it is not completed

**Comment by Daksh-134** [comment]
I have added the files and created a PR @sanjaysah101
